
package com.colsanitas.loginadmin.administracion.integration.biosanitas;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-09/10/2010 09:17 PM(mockbuild)-
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "BioSanitasWSException", targetNamespace = "http://ejb.business.ws.biosanitas.osi.com/")
public class BioSanitasWSException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BioSanitasWSException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public BioSanitasWSException_Exception(String message, BioSanitasWSException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public BioSanitasWSException_Exception(String message, BioSanitasWSException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.colsanitas.loginadmin.administracion.integration.biosanitas.BioSanitasWSException
     */
    public BioSanitasWSException getFaultInfo() {
        return faultInfo;
    }

}
