
package com.colsanitas.loginadmin.administracion.integration.biosanitas;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-09/10/2010 09:17 PM(mockbuild)-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "LoginAdminEJBWS", targetNamespace = "http://ejb.business.ws.biosanitas.osi.com/")
public interface LoginAdminEJBWS {


    /**
     * 
     * @param dtoIn
     * @return
     *     returns com.colsanitas.loginadmin.administracion.integration.biosanitas.DatosPrestadorDTO
     * @throws PrestadorNotFoundExcepcion_Exception
     * @throws BioSanitasWSException_Exception
     * @throws PrestadorNotMigratedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaDatosPrestadorByID", targetNamespace = "http://ejb.business.ws.biosanitas.osi.com/", className = "com.colsanitas.loginadmin.administracion.integration.biosanitas.ConsultaDatosPrestadorByID")
    @ResponseWrapper(localName = "consultaDatosPrestadorByIDResponse", targetNamespace = "http://ejb.business.ws.biosanitas.osi.com/", className = "com.colsanitas.loginadmin.administracion.integration.biosanitas.ConsultaDatosPrestadorByIDResponse")
    public DatosPrestadorDTO consultaDatosPrestadorByID(
        @WebParam(name = "dtoIn", targetNamespace = "")
        DatosPrestadorDTO dtoIn)
        throws BioSanitasWSException_Exception, PrestadorNotFoundExcepcion_Exception, PrestadorNotMigratedException_Exception
    ;

    /**
     * 
     * @param dtoIn
     * @return
     *     returns java.util.List<com.colsanitas.loginadmin.administracion.integration.biosanitas.SucursalesByPrestadorDTO>
     * @throws PrestadorNotFoundExcepcion_Exception
     * @throws BioSanitasWSException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaSucursalesPrestadorByID", targetNamespace = "http://ejb.business.ws.biosanitas.osi.com/", className = "com.colsanitas.loginadmin.administracion.integration.biosanitas.ConsultaSucursalesPrestadorByID")
    @ResponseWrapper(localName = "consultaSucursalesPrestadorByIDResponse", targetNamespace = "http://ejb.business.ws.biosanitas.osi.com/", className = "com.colsanitas.loginadmin.administracion.integration.biosanitas.ConsultaSucursalesPrestadorByIDResponse")
    public List<SucursalesByPrestadorDTO> consultaSucursalesPrestadorByID(
        @WebParam(name = "dtoIn", targetNamespace = "")
        SucursalesByPrestadorDTO dtoIn)
        throws BioSanitasWSException_Exception, PrestadorNotFoundExcepcion_Exception
    ;

}
