
package com.colsanitas.loginadmin.administracion.integration.biosanitas;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

import com.osi.gaudi.cfg.Configurator;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-09/10/2010 09:17 PM(mockbuild)-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "LoginAdminEJBWSService", targetNamespace = "http://ejb.business.ws.biosanitas.osi.com/", wsdlLocation = "http://pruebas.colsanitas.com:8380/BioSanitasWS/LoginAdminWS?wsdl")
public class LoginAdminEJBWSService
    extends Service
{

    private final static URL LOGINADMINEJBWSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.colsanitas.loginadmin.administracion.integration.biosanitas.LoginAdminEJBWSService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.colsanitas.loginadmin.administracion.integration.biosanitas.LoginAdminEJBWSService.class.getResource(".");
            url = new URL(baseUrl, Configurator.getInstance().getString("administracion","wsdlLocationBioSanitas","http://neptuno.colsanitas.com:8580/BioSanitasWS/LoginAdminWS?wsdl"));
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: '"+Configurator.getInstance().getString("administracion","wsdlLocationBioSanitas","http://pruebas.colsanitas.com:8380/BioSanitasWS/LoginAdminWS?wsdl")+"', retrying as a local file");
            logger.warning(e.getMessage());
        }
        LOGINADMINEJBWSSERVICE_WSDL_LOCATION = url;
    }

    public LoginAdminEJBWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoginAdminEJBWSService() {
        super(LOGINADMINEJBWSSERVICE_WSDL_LOCATION, new QName("http://ejb.business.ws.biosanitas.osi.com/", "LoginAdminEJBWSService"));
    }

    /**
     * 
     * @return
     *     returns LoginAdminEJBWS
     */
    @WebEndpoint(name = "LoginAdminEJBWSPort")
    public LoginAdminEJBWS getLoginAdminEJBWSPort() {
        return super.getPort(new QName("http://ejb.business.ws.biosanitas.osi.com/", "LoginAdminEJBWSPort"), LoginAdminEJBWS.class);
    }

}
