INSERT INTO WS_ELEMENTO (id_elemento,id_metodo,id_elemento_padre,nombre,minima_ocurrencia,maxima_ocurrencia,nivel,secuencia,valor) SELECT SEQ_PK_WS_ELEMENTO.NEXTVAL, M.id_metodo, NULL, 'soapenv:Envelope', /*minima_ocurrencia*/1, /*maxima_ocurrencia*/1, 1, 1, NULL FROM WS_SERVICIO S, WS_METODO M WHERE S.aplicacion = 'LOGIN_ADMIN' AND S.nombre = 'Prestadores' AND M.id_servicio = S.id_servicio AND M.nombre = 'http://www.colsanitas.com/Prestadores/CuadroMedico';

INSERT INTO WS_PROPIEDAD (id_propiedad,nombre,opcional,valor) VALUES (SEQ_PK_WS_PROPIEDAD.NEXTVAL,'xmlns:nof','N','http://colsanitas.com/osi/comun/nofuncionales');
INSERT INTO WS_ELEMENTO_PROPIEDAD (id_elemento, id_propiedad) VALUES (SEQ_PK_WS_ELEMENTO.CURRVAL, SEQ_PK_WS_PROPIEDAD.CURRVAL);
INSERT INTO WS_PROPIEDAD (id_propiedad,nombre,opcional,valor) VALUES (SEQ_PK_WS_PROPIEDAD.NEXTVAL,'xmlns:per','N','http://colsanitas.com/osi/comun/persona');
INSERT INTO WS_ELEMENTO_PROPIEDAD (id_elemento, id_propiedad) VALUES (SEQ_PK_WS_ELEMENTO.CURRVAL, SEQ_PK_WS_PROPIEDAD.CURRVAL);
INSERT INTO WS_PROPIEDAD (id_propiedad,nombre,opcional,valor) VALUES (SEQ_PK_WS_PROPIEDAD.NEXTVAL,'xmlns:pres','N','http://colsanitas.com/PrestadoresServicio/');
INSERT INTO WS_ELEMENTO_PROPIEDAD (id_elemento, id_propiedad) VALUES (SEQ_PK_WS_ELEMENTO.CURRVAL, SEQ_PK_WS_PROPIEDAD.CURRVAL);
INSERT INTO WS_PROPIEDAD (id_propiedad,nombre,opcional,valor) VALUES (SEQ_PK_WS_PROPIEDAD.NEXTVAL,'xmlns:pres1','N','http://colsanitas.com/osi/comun/prestadores');
INSERT INTO WS_ELEMENTO_PROPIEDAD (id_elemento, id_propiedad) VALUES (SEQ_PK_WS_ELEMENTO.CURRVAL, SEQ_PK_WS_PROPIEDAD.CURRVAL);
INSERT INTO WS_PROPIEDAD (id_propiedad,nombre,opcional,valor) VALUES (SEQ_PK_WS_PROPIEDAD.NEXTVAL,'xmlns:soapenv','N','http://schemas.xmlsoap.org/soap/envelope/');
INSERT INTO WS_ELEMENTO_PROPIEDAD (id_elemento, id_propiedad) VALUES (SEQ_PK_WS_ELEMENTO.CURRVAL, SEQ_PK_WS_PROPIEDAD.CURRVAL);
INSERT INTO WS_PROPIEDAD (id_propiedad,nombre,opcional,valor) VALUES (SEQ_PK_WS_PROPIEDAD.NEXTVAL,'xmlns:srv','N','http://colsanitas.com/osi/srv');
INSERT INTO WS_ELEMENTO_PROPIEDAD (id_elemento, id_propiedad) VALUES (SEQ_PK_WS_ELEMENTO.CURRVAL, SEQ_PK_WS_PROPIEDAD.CURRVAL);
INSERT INTO WS_PROPIEDAD (id_propiedad,nombre,opcional,valor) VALUES (SEQ_PK_WS_PROPIEDAD.NEXTVAL,'xmlns:ubic','N','http://colsanitas.com/osi/comun/ubicacion');
INSERT INTO WS_ELEMENTO_PROPIEDAD (id_elemento, id_propiedad) VALUES (SEQ_PK_WS_ELEMENTO.CURRVAL, SEQ_PK_WS_PROPIEDAD.CURRVAL);

INSERT INTO WS_ELEMENTO (id_elemento,id_metodo,id_elemento_padre,nombre,minima_ocurrencia,maxima_ocurrencia,nivel,secuencia,valor) SELECT SEQ_PK_WS_ELEMENTO.NEXTVAL, M.id_metodo, P.id_elemento, 'soapenv:Header', /*minima_ocurrencia*/1, /*maxima_ocurrencia*/1, 2, 1, NULL FROM WS_SERVICIO S, WS_METODO M, WS_ELEMENTO P WHERE S.aplicacion = 'LOGIN_ADMIN' AND S.nombre = 'Prestadores' AND M.id_servicio = S.id_servicio AND M.nombre = 'http://www.colsanitas.com/Prestadores/CuadroMedico' AND P.id_metodo = M.id_metodo AND P.nombre = 'soapenv:Envelope' AND P.nivel = 1;
INSERT INTO WS_ELEMENTO (id_elemento,id_metodo,id_elemento_padre,nombre,minima_ocurrencia,maxima_ocurrencia,nivel,secuencia,valor) SELECT SEQ_PK_WS_ELEMENTO.NEXTVAL, M.id_metodo, P.id_elemento, 'pres:HeaderRqust', /*minima_ocurrencia*/1, /*maxima_ocurrencia*/1, 3, 1, NULL FROM WS_SERVICIO S, WS_METODO M, WS_ELEMENTO P WHERE S.aplicacion = 'LOGIN_ADMIN' AND S.nombre = 'Prestadores' AND M.id_servicio = S.id_servicio AND M.nombre = 'http://www.colsanitas.com/Prestadores/CuadroMedico' AND P.id_metodo = M.id_metodo AND P.nombre = 'soapenv:Header' AND P.nivel = 2;
INSERT INTO WS_ELEMENTO (id_elemento,id_metodo,id_elemento_padre,nombre,minima_ocurrencia,maxima_ocurrencia,nivel,secuencia,valor) SELECT SEQ_PK_WS_ELEMENTO.NEXTVAL, M.id_metodo, P.id_elemento, 'pres:header', /*minima_ocurrencia*/1, /*maxima_ocurrencia*/1, 4, 1, NULL FROM WS_SERVICIO S, WS_METODO M, WS_ELEMENTO P WHERE S.aplicacion = 'LOGIN_ADMIN' AND S.nombre = 'Prestadores' AND M.id_servicio = S.id_servicio AND M.nombre = 'http://www.colsanitas.com/Prestadores/CuadroMedico' AND P.id_metodo = M.id_metodo AND P.nombre = 'pres:HeaderRqust' AND P.nivel = 3;
INSERT INTO WS_ELEMENTO (id_elemento,id_metodo,id_elemento_padre,nombre,minima_ocurrencia,maxima_ocurrencia,nivel,secuencia,valor) SELECT SEQ_PK_WS_ELEMENTO.NEXTVAL, M.id_metodo, P.id_elemento, 'nof:messageHeader', /*minima_ocurrencia*/1, /*maxima_ocurrencia*/1, 5, 1, NULL FROM WS_SERVICIO S, WS_METODO M, WS_ELEMENTO P WHERE S.aplicacion = 'LOGIN_ADMIN' AND S.nombre = 'Prestadores' AND M.id_servicio = S.id_servicio AND M.nombre = 'http://www.colsanitas.com/Prestadores/CuadroMedico' AND P.id_metodo = M.id_metodo AND P.nombre = 'pres:header' AND P.nivel = 4;
INSERT INTO WS_ELEMENTO (id_elemento,id_metodo,id_elemento_padre,nombre,minima_ocurrencia,maxima_ocurrencia,nivel,secuencia,valor) SELECT SEQ_PK_WS_ELEMENTO.NEXTVAL, M.id_metodo, P.id_elemento, 'nof:messageInfo', /*minima_ocurrencia*/1, /*maxima_ocurrencia*/1, 6, 1, NULL FROM WS_SERVICIO S, WS_METODO M, WS_ELEMENTO P WHERE S.aplicacion = 'LOGIN_ADMIN' AND S.nombre = 'Prestadores' AND M.id_servicio = S.id_servicio AND M.nombre = 'http://www.colsanitas.com/Prestadores/CuadroMedico' AND P.id_metodo = M.id_metodo AND P.nombre = 'nof:messageHeader' AND P.nivel = 5;
INSERT INTO WS_ELEMENTO (id_elemento,id_metodo,id_elemento_padre,nombre,minima_ocurrencia,maxima_ocurrencia,nivel,secuencia,valor) SELECT SEQ_PK_WS_ELEMENTO.NEXTVAL, M.id_metodo, P.id_elemento, 'nof:fechaTime', /*minima_ocurrencia*/1, /*maxima_ocurrencia*/1, 7, 1, '$FECHA_CONS$' FROM WS_SERVICIO S, WS_METODO M, WS_ELEMENTO P WHERE S.aplicacion = 'LOGIN_ADMIN' AND S.nombre = 'Prestadores' AND M.id_servicio = S.id_servicio AND M.nombre = 'http://www.colsanitas.com/Prestadores/CuadroMedico' AND P.id_metodo = M.id_metodo AND P.nombre = 'nof:messageInfo' AND P.nivel = 6;
INSERT INTO WS_ELEMENTO (id_elemento,id_metodo,id_elemento_padre,nombre,minima_ocurrencia,maxima_ocurrencia,nivel,secuencia,valor) SELECT SEQ_PK_WS_ELEMENTO.NEXTVAL, M.id_metodo, P.id_elemento, 'nof:tipoConsulta', /*minima_ocurrencia*/1, /*maxima_ocurrencia*/1, 7, 2, '3' FROM WS_SERVICIO S, WS_METODO M, WS_ELEMENTO P WHERE S.aplicacion = 'LOGIN_ADMIN' AND S.nombre = 'Prestadores' AND M.id_servicio = S.id_servicio AND M.nombre = 'http://www.colsanitas.com/Prestadores/CuadroMedico' AND P.id_metodo = M.id_metodo AND P.nombre = 'nof:messageInfo' AND P.nivel = 6;
INSERT INTO WS_ELEMENTO (id_elemento,id_metodo,id_elemento_padre,nombre,minima_ocurrencia,maxima_ocurrencia,nivel,secuencia,valor) SELECT SEQ_PK_WS_ELEMENTO.NEXTVAL, M.id_metodo, P.id_elemento, 'soapenv:Body', /*minima_ocurrencia*/1, /*maxima_ocurrencia*/1, 2, 2, NULL FROM WS_SERVICIO S, WS_METODO M, WS_ELEMENTO P WHERE S.aplicacion = 'LOGIN_ADMIN' AND S.nombre = 'Prestadores' AND M.id_servicio = S.id_servicio AND M.nombre = 'http://www.colsanitas.com/Prestadores/CuadroMedico' AND P.id_metodo = M.id_metodo AND P.nombre = 'soapenv:Envelope' AND P.nivel = 1;
INSERT INTO WS_ELEMENTO (id_elemento,id_metodo,id_elemento_padre,nombre,minima_ocurrencia,maxima_ocurrencia,nivel,secuencia,valor) SELECT SEQ_PK_WS_ELEMENTO.NEXTVAL, M.id_metodo, P.id_elemento, 'pres:CuadroMedicoEnt', /*minima_ocurrencia*/1, /*maxima_ocurrencia*/1, 3, 1, NULL FROM WS_SERVICIO S, WS_METODO M, WS_ELEMENTO P WHERE S.aplicacion = 'LOGIN_ADMIN' AND S.nombre = 'Prestadores' AND M.id_servicio = S.id_servicio AND M.nombre = 'http://www.colsanitas.com/Prestadores/CuadroMedico' AND P.id_metodo = M.id_metodo AND P.nombre = 'soapenv:Body' AND P.nivel = 2;
INSERT INTO WS_ELEMENTO (id_elemento,id_metodo,id_elemento_padre,nombre,minima_ocurrencia,maxima_ocurrencia,nivel,secuencia,valor) SELECT SEQ_PK_WS_ELEMENTO.NEXTVAL, M.id_metodo, P.id_elemento, 'pres:cuadroMedicoEnt', /*minima_ocurrencia*/1, /*maxima_ocurrencia*/1, 4, 1, NULL FROM WS_SERVICIO S, WS_METODO M, WS_ELEMENTO P WHERE S.aplicacion = 'LOGIN_ADMIN' AND S.nombre = 'Prestadores' AND M.id_servicio = S.id_servicio AND M.nombre = 'http://www.colsanitas.com/Prestadores/CuadroMedico' AND P.id_metodo = M.id_metodo AND P.nombre = 'pres:CuadroMedicoEnt' AND P.nivel = 3;
INSERT INTO WS_ELEMENTO (id_elemento,id_metodo,id_elemento_padre,nombre,minima_ocurrencia,maxima_ocurrencia,nivel,secuencia,valor) SELECT SEQ_PK_WS_ELEMENTO.NEXTVAL, M.id_metodo, P.id_elemento, 'srv:CuadroMedico', /*minima_ocurrencia*/1, /*maxima_ocurrencia*/1, 5, 1, NULL FROM WS_SERVICIO S, WS_METODO M, WS_ELEMENTO P WHERE S.aplicacion = 'LOGIN_ADMIN' AND S.nombre = 'Prestadores' AND M.id_servicio = S.id_servicio AND M.nombre = 'http://www.colsanitas.com/Prestadores/CuadroMedico' AND P.id_metodo = M.id_metodo AND P.nombre = 'pres:cuadroMedicoEnt' AND P.nivel = 4;
INSERT INTO WS_ELEMENTO (id_elemento,id_metodo,id_elemento_padre,nombre,minima_ocurrencia,maxima_ocurrencia,nivel,secuencia,valor) SELECT SEQ_PK_WS_ELEMENTO.NEXTVAL, M.id_metodo, P.id_elemento, 'srv:identificacionPrestador', /*minima_ocurrencia*/1, /*maxima_ocurrencia*/1, 6, 1, NULL FROM WS_SERVICIO S, WS_METODO M, WS_ELEMENTO P WHERE S.aplicacion = 'LOGIN_ADMIN' AND S.nombre = 'Prestadores' AND M.id_servicio = S.id_servicio AND M.nombre = 'http://www.colsanitas.com/Prestadores/CuadroMedico' AND P.id_metodo = M.id_metodo AND P.nombre = 'srv:CuadroMedico' AND P.nivel = 5;
INSERT INTO WS_ELEMENTO (id_elemento,id_metodo,id_elemento_padre,nombre,minima_ocurrencia,maxima_ocurrencia,nivel,secuencia,valor) SELECT SEQ_PK_WS_ELEMENTO.NEXTVAL, M.id_metodo, P.id_elemento, 'per:numIdentificacion', /*minima_ocurrencia*/1, /*maxima_ocurrencia*/1, 7, 1, '$NRO_ID$' FROM WS_SERVICIO S, WS_METODO M, WS_ELEMENTO P WHERE S.aplicacion = 'LOGIN_ADMIN' AND S.nombre = 'Prestadores' AND M.id_servicio = S.id_servicio AND M.nombre = 'http://www.colsanitas.com/Prestadores/CuadroMedico' AND P.id_metodo = M.id_metodo AND P.nombre = 'srv:identificacionPrestador' AND P.nivel = 6;
INSERT INTO WS_ELEMENTO (id_elemento,id_metodo,id_elemento_padre,nombre,minima_ocurrencia,maxima_ocurrencia,nivel,secuencia,valor) SELECT SEQ_PK_WS_ELEMENTO.NEXTVAL, M.id_metodo, P.id_elemento, 'per:tipoIdentificacion', /*minima_ocurrencia*/1, /*maxima_ocurrencia*/1, 7, 2, '$TIPO_ID$' FROM WS_SERVICIO S, WS_METODO M, WS_ELEMENTO P WHERE S.aplicacion = 'LOGIN_ADMIN' AND S.nombre = 'Prestadores' AND M.id_servicio = S.id_servicio AND M.nombre = 'http://www.colsanitas.com/Prestadores/CuadroMedico' AND P.id_metodo = M.id_metodo AND P.nombre = 'srv:identificacionPrestador' AND P.nivel = 6;
INSERT INTO WS_ELEMENTO (id_elemento,id_metodo,id_elemento_padre,nombre,minima_ocurrencia,maxima_ocurrencia,nivel,secuencia,valor) SELECT SEQ_PK_WS_ELEMENTO.NEXTVAL, M.id_metodo, P.id_elemento, 'srv:nomSucursalPrestador', /*minima_ocurrencia*/0, /*maxima_ocurrencia*/1, 6, 2, '$NOM_SUC$' FROM WS_SERVICIO S, WS_METODO M, WS_ELEMENTO P WHERE S.aplicacion = 'LOGIN_ADMIN' AND S.nombre = 'Prestadores' AND M.id_servicio = S.id_servicio AND M.nombre = 'http://www.colsanitas.com/Prestadores/CuadroMedico' AND P.id_metodo = M.id_metodo AND P.nombre = 'srv:CuadroMedico' AND P.nivel = 5;

COMMIT;
