package com.colsanitas.loginadmin.administracion.entity;

// Generated 17  2011 17:36:03 by Hibernate Tools 3.4.0.CR1

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlTransient;

import org.hibernate.envers.Audited;
import org.hibernate.envers.RelationTargetAuditMode;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

import com.osi.his.sistema.util.EntityClass;

/**
 * AuthTbPrestador generated by hbm2java
 */
@Entity
@Table(name = "AUTH_TB_PRESTADOR")
@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
public class PrestadorEntity extends EntityClass implements LocalEntity {


	private static final long serialVersionUID = -5988377143212911307L;
	
	private Long prestadorId;
	private Long cdperson;
	private String sucursal;
	private String razonSocial;
	private String tipoId;
	private String numId;
	
	@Audited
	private boolean estado;

	public PrestadorEntity() {
	}

	public PrestadorEntity(Long prestadorId, String razonSocial, Long cdperson,
			String tipoId, String numId) {
		this.prestadorId = prestadorId;
		this.razonSocial = razonSocial;
		this.cdperson = cdperson;
		this.tipoId = tipoId;
		this.numId = numId;
	}

	public PrestadorEntity(Long prestadorId, Long cdperson,
			String tipoId, String numId, Set<RelacionEntity> relaciones) {
		this.prestadorId = prestadorId;
		this.cdperson = cdperson;
		this.tipoId = tipoId;
		this.numId = numId;
	}

	@Id
	@Column(name = "PRESTADOR_ID", unique = true, nullable = false, precision = 22, scale = 0)
	@NotNull
    @SequenceGenerator(allocationSize=1, name = "AUTH_SQ_PRESTADOR", sequenceName = "AUTH_SQ_PRESTADOR")
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "AUTH_SQ_PRESTADOR")
	public Long getPrestadorId() {
		return this.prestadorId;
	}

	public void setPrestadorId(Long prestadorId) {
		this.prestadorId = prestadorId;
	}

	@Column(name = "CDPERSON", nullable = false, precision = 22, scale = 0)
	@NotNull
	public Long getCdperson() {
		return this.cdperson;
	}

	public void setCdperson(Long cdperson) {
		this.cdperson = cdperson;
	}

	@Column(name = "TIPO_ID", nullable = false, length = 2)
	@NotNull
	@Length(max = 2)
	public String getTipoId() {
		return this.tipoId;
	}

	public void setTipoId(String tipoId) {
		this.tipoId = tipoId;
	}

	@Column(name = "NUM_ID", nullable = false, length = 32)
	@NotNull
	@Length(max = 32)
	public String getNumId() {
		return this.numId;
	}
	
	public void setNumId(String numId) {
		this.numId = numId;
	}


	public void setSucursal(String sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "SUCURSAL_ID", nullable = false, length = 32)
	@NotNull
	@Length(max = 32)
	public String getSucursal() {
		return this.sucursal;
	}

	@Column(name = "RAZONSOCIAL", nullable = false, length = 128)
	@NotNull
	@Length(max = 128)
	public String getRazonSocial() {
		return this.razonSocial;
	}

	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}
	
	@XmlTransient
	@Column(name = "ESTADO", nullable = false, precision = 1, scale = 0)
	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

}
