package com.colsanitas.loginadmin.administracion.entity;

// Generated 17 août 2011 17:36:03 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlTransient;

import org.hibernate.envers.Audited;
import org.hibernate.envers.RelationTargetAuditMode;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

import com.osi.gaudi.security.authorization.clientews.Role;

/**
 * AuthTbPrestador generated by hbm2java
 */
@Entity
@Table(name = "AUTH_TB_USER_ROLE")
@Audited
@NamedQueries({
	@NamedQuery(name=UserRoleEntity.FIND_USER_ROLE_BY_PREST,
				query = " SELECT USRO " +
						"  FROM UserRoleEntity USRO " +
						"  WHERE USRO.prestadorId = :id_prestador " +
						"  AND USRO.roleId = :id_role ")
})
public class UserRoleEntity implements LocalEntity {

	private static final long serialVersionUID = 8469018645371591022L;
	
	//NamedQuery
	public static final String FIND_USER_ROLE_BY_PREST = "FIND_USER_ROLE_BY_PREST";
	
	private Long id;
	
	@Audited
	private Long roleId;
	
	@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
	private String userId;
	
	@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
	private Long prestadorId;
	
	private boolean selected;
	
	private String accion;
	
	@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
	private String tipoRolLA;
	
	private Role role;
	
	@Transient
	private boolean administradorDominio;
	
	public UserRoleEntity() {
	}

	public UserRoleEntity(Long userRoleId, String userId, Long roleId ) {
		this.id = userRoleId;
		this.userId = userId;
		this.roleId = roleId;
	}
	
    @SequenceGenerator(name="AUTH_SQ_USERS_ROLE", sequenceName="AUTH_SQ_USERS_ROLE", allocationSize=1)
    @Id
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="AUTH_SQ_USERS_ROLE")
    @Column(name="user_role_id")
    public Long getId() {
		return this.id;
	}

	public void setId(Long prestadorId) {
		this.id = prestadorId;
	}
	
	@Column(name = "USER_ID", unique = true, nullable = false, length = 64)
	@NotNull
	@Length(max = 64)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}
	
	@Column(name = "ROLE_ID", unique = true, nullable = false, length = 5)
	@NotNull
	public Long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}
	
	@Column(name = "PRESTADOR_ID", unique = true, nullable = false, precision = 22, scale = 0)
    public Long getPrestadorId() {
		return this.prestadorId;
	}

	public void setPrestadorId(Long prestadorId) {
		this.prestadorId = prestadorId;
	}

	@Transient
	public boolean isSelected() {
		return selected;
	}

	public void setSelected(boolean selected) {
		this.selected = selected;
	}
	
	@Transient
	public String getAccion() {
		return accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}
	
	@Transient
	public Role getRole() {
		return role;
	}

	public void setRole(Role role) {
		this.role = role;
	}
	
	@Column(name = "LA_TIPO_ROL")
	public String getTipoRolLA() {
		return tipoRolLA;
	}

	public void setTipoRolLA(String tipoRolLA) {
		this.tipoRolLA = tipoRolLA;
	}
	
	@Transient
	@XmlTransient
	public boolean isAdministradorDominio() {
		return administradorDominio;
	}
	
	@Transient
	@XmlTransient
	public boolean getAdministradorDominio() {
		return administradorDominio;
	}

	@Transient
	public void setAdministradorDominio(boolean administradorDominio) {
		this.administradorDominio = administradorDominio;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((prestadorId == null) ? 0 : prestadorId.hashCode());
		result = prime * result + ((roleId == null) ? 0 : roleId.hashCode());
		result = prime * result + ((userId == null) ? 0 : userId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		UserRoleEntity other = (UserRoleEntity) obj;
		if (prestadorId == null) {
			if (other.prestadorId != null)
				return false;
		} else if (!prestadorId.equals(other.prestadorId))
			return false;
		if (roleId == null) {
			if (other.roleId != null)
				return false;
		} else if (!roleId.equals(other.roleId))
			return false;
		if (userId == null) {
			if (other.userId != null)
				return false;
		} else if (!userId.equals(other.userId))
			return false;
		return true;
	}

	

}
