package com.osi.his.sistema.util;

import java.io.InputStream;
import java.io.Serializable;
import java.util.HashMap;
import com.osi.gpm.util.GPMProperties;

/**
 * 
 * @author gstovar
 *
 */

public final class LoginBusinessProperties implements Serializable{
	private static final long serialVersionUID = 1774460636195268712L;
	
	//Patron singleton
	private static LoginBusinessProperties instance;
	private HashMap<String, String> config;
	
	//VARIABLES DE SISTEMA DE SEGURIDAD
	public final static String SSO_SERVER_LOG_OUT = "SSO_SERVER_LOG_OUT";
	
	// CONFIGURACION DE DIRETORIO TEMPORAL DE ARCHIVOS ADJUNTOS Y CARGUES MASIVOS
	public final static String PROP_NMA_APP_SERVER_TEMP_PATH = "nma.appserver.tempPath";
	public final static String PROP_CRON_DELETE_TMP_FILES = "nma.cronExpression.deleteTmpFiles";
	public final static String PROP_CRON_DUMMY = "nma.cronExpression.jobDummy";
	public final static String PROP_CRON_TEMP_RANGO_LAST_MODIFIED = "nma.cronExpression.tmp.rango.last.modified";
	
	public final static String FORMATO_PREFIJO_ANEXO_RADICACION_FILE_SERVER = "FORMATO_PREFIJO_ANEXO_RADICACION_FILE_SERVER";
	public final static String FORMATO_SPLIT_RADICACION_ADJUNTO = "FORMATO_SPLIT_RADICACION_ADJUNTO";
	
	public final static String ID_DOMAIN = "ID_DOMAIN";
	
	public final static String MIN_SIZE_FILE = "MIN_SIZE_FILE";
	public final static String MAX_SIZE_FILE_ADJUNTO_OM = "MAX_SIZE_FILE_ADJUNTO_OM";
	public final static String MAX_SIZE_FILE_CARGUE_MASIVO = "MAX_SIZE_FILE_CARGUE_MASIVO";
	
	public final static String FORMATO_DATE_APLICACION_HORA = "FORMATO_DATE_APLICACION_HORA";
	
	public final static String FORMATO_PREFIJO_RESPUESTA_CARGUE_MASIVO = "FORMATO_PREFIJO_RESPUESTA_CARGUE_MASIVO";
	public final static String NOMBRE_ARCHIVO_RES_MASIVO_AGRUPACION_SERVICIO = "NOMBRE_ARCHIVO_RES_MASIVO_AGRUPACION_SERVICIO";
	public final static String NOMBRE_ARCHIVO_RES_MASIVO_GLOSARIO_SERVICIO = "NOMBRE_ARCHIVO_RES_MASIVO_GLOSARIO_SERVICIO";
	public final static String NOMBRE_ARCHIVO_RES_MASIVO_PRESTADOR_INSTITUCION = "NOMBRE_ARCHIVO_RES_MASIVO_PRESTADOR_INSTITUCION";
	public final static String NOMBRE_ARCHIVO_RES_MASIVO_PRESTADOR_PRIORIDAD = "NOMBRE_ARCHIVO_RES_MASIVO_PRESTADOR_PRIORIDAD";
	public final static String NOMBRE_ARCHIVO_RES_MASIVO_PRESTADOR_NO_REQ_AUT = "NOMBRE_ARCHIVO_RES_MASIVO_PRESTADOR_NO_REQ_AUT";
	
	

	// CONFIGURACION DE TIPO BUSQUEDA PARA RADICACION
	public final static String RADICACION_IDENTIFICACION = "RADICACION_IDENTIFICACION";
	public final static String RADICACION_CONTRATO = "RADICACION_CONTRATO";
	public final static String RADICACION_NOMBRE = "RADICACION_NOMBRE";
	
	// CONFIGURACION DE TIPO BUSQUEDA POR SERVICIOS
	public final static String RADICACION_SERVICIOS_DESCRIPCION = "RADICACION_SERVICIOS_DESCRIPCION";
	public final static String RADICACION_SERVICIOS_CODIGO = "RADICACION_SERVICIOS_CODIGO";
	public final static String TIPO_OBSERVACION_GESTION = "TIPO_OBSERVACION_GESTION";
	public final static String TIPO_OBSERVACION_PRESTADOR = "TIPO_OBSERVACION_PRESTADOR";
	public final static String ESTADO_ACTIVO_ENTIDAD = "ESTADO_ACTIVO_ENTIDAD";
	public final static String ESTADO_INACTIVO_ENTIDAD = "ESTADO_INACTIVO_ENTIDAD";
	
	
	// PARAMETROS INICIALES DE LA RADICACION MOTIVO Y ESTADO DEL SERVICIO
	public static String ESTADO_SERVICIO_RA = "ESTADO_SERVICIO_RA";
	public static String VALOR_ESTADO_INICIAL_RA = "VALOR_ESTADO_INICIAL_RA";
	public static String MOTIVO_SERVICIO_RA = "MOTIVO_SERVICIO_RA";
	public static String VALOR_MOTIVO_INICIAL_RA = "VALOR_MOTIVO_INICIAL_RA";
	
	// CONFIGURACION DE UPLOAD DE ARCHIVOS ANEXOS Y CARGUES MASIVOS
	public final static String CANTIDAD_MAX_ARCHIVOS_UPLOAD_MASIVO = "CANTIDAD_MAX_ARCHIVOS_UPLOAD_MASIVO";
	public final static String CANTIDAD_MAX_ARCHIVOS_UPLOAD_ANEXOS = "CANTIDAD_MAX_ARCHIVOS_UPLOAD_ANEXOS";
	
	public final static String CONCATENA_RADICADOR = "CONCATENA_RADICADOR";
	
	public final static String TIPO_RADICACION = "TIPO_RADICACION"; 
	public final static String ESTADO_RADICACION = "ESTADO_RADICACION";
	public final static String MOTIVO_RADICACION = "MOTIVO_RADICACION";
	public final static String RADICACION_TIPO = "RADICACION_TIPO";
	
	// CONFIGURACION DE LA LISTA DE CONSULTAR RADICACION POR TIPO DE CONSULTA
	public final static String CONSULTA_RADICACION_POR_IDENTIFICACION = "CONSULTA_RADICACION_POR_IDENTIFICACION";
	public final static String CONSULTA_RADICACION_POR_COMPANIA = "CONSULTA_RADICACION_POR_COMPANIA";
	public final static String CONSULTA_RADICACION_POR_CONTRATO = "CONSULTA_RADICACION_POR_CONTRATO";
	public final static String CONSULTA_RADICACION_POR_RADICACION = "CONSULTA_RADICACION_POR_RADICACION";
	
	public final static String ROL_USUARIO = "ROL_USUARIO";
	public final static String ROL_PRESTADOR_RADICADOR = "ROL_PRESTADOR_RADICADOR";
	public final static String ROL_FUNCIONARIO = "ROL_FUNCIONARIO";
	
	public final static String LOGIN_USER_SIN_PERMISOS = "LOGIN_USER_SIN_PERMISOS";
	
	public final static String ROL_USUARIO_GAUDI = "ROL_USUARIO_GAUDI";
	public final static String ROL_PRESTADOR_RADICADOR_GAUDI = "ROL_PRESTADOR_RADICADOR_GAUDI";
	public final static String ROL_FUNCIONARIO_GAUDI = "ROL_FUNCIONARIO_GAUDI";
	
	public final static String ROL_ITERADOR_SIMULADOR = "ROL_ITERADOR_SIMULADOR";
	
	// CONFIGURACION DE CUADRO DIRECCIONAMIENTO
	public final static String AGRUPACION_SERVICIOS = "AGRUPACION_SERVICIOS";
	public final static String GLOSARIO_SERVICIOS = "GLOSARIO_SERVICIOS";
	public final static String CARGA_PRESTADORES = "CARGA_PRESTADORES";
	public final static String INFORMACION_CONTACTO_PRESTADOR = "INFORMACION_CONTACTO_PRESTADOR";
	public final static String INFRAESTRUCTURA_OSI = "INFRAESTRUCTURA_OSI";
	public final static String INSTITUCIONES_PRESTADORES_NATURALES = "INSTITUCIONES_PRESTADORES_NATURALES";
	public final static String MENSAJES_PRESTADOR = "MENSAJES_PRESTADOR";
	public final static String PRESTADORES_NO_ORDENANTES = "PRESTADORES_NO_ORDENANTES";
	public final static String PRESTADORES_NO_VISIBLES = "PRESTADORES_NO_VISIBLES";
	public final static String PRIORIDAD_PRESTADORES = "PRIORIDAD_PRESTADORES";
	public final static String SERVICIOS_NO_REQUIEREN_AUTORIZACION_PRESTADOR = "SERVICIOS_NO_REQUIEREN_AUTORIZACION_PRESTADOR";
	
	public final static String CONDICION_ROL_VISIBLE_SI = "CONDICION_ROL_VISIBLE_SI";
	
	//CONFIGURACION DE CARGUE MASIVO DE ARCHIVOS
	public final static String TOTAL_LINEAS_ARCHIVO = "TOTAL_LINEAS_ARCHIVO";
	public final static String CHARSET_CARGUE_MASIVO = "CHARSET_CARGUE_MASIVO";
	public final static String TOTAL_LINEAS_ARCHIVO_ERROR = "TOTAL_LINEAS_ARCHIVO_ERROR";
	public final static String TOTAL_LINEAS_ARCHIVO_EXITO = "TOTAL_LINEAS_ARCHIVO_EXITO";
	public final static String ERROR_LINEA_ARCHIVO_MASIVO = "ERROR_LINEA_ARCHIVO_MASIVO";
	
	//MENSAJES DE ERROR DE CARGUES MASIVOS
	//----------mensajes de cargue masivo de agrupaciones de servicios
	public final static String MASIVO_AGRUPACION_NO_RANGO_COD_SERV = "MASIVO_AGRUPACION_NO_RANGO_COD_SERV";
	public final static String MASIVO_AGRUPACION_RANGO_COD_SERV = "MASIVO_AGRUPACION_RANGO_COD_SERV";
	public final static String MASIVO_AGRUPACION_RANGO_INCOMPLETO = "MASIVO_AGRUPACION_RANGO_INCOMPLETO";
	public final static String MASIVO_AGRUPACION_CANTIDAD_DATOS_ERROR = "MASIVO_AGRUPACION_CANTIDAD_DATOS_ERROR";
	public final static String MASIVO_AGRUPACION_NO_CODIGO_ESTADO = "MASIVO_AGRUPACION_NO_CODIGO_ESTADO";
	public final static String MASIVO_GLOSARIO_NO_CODIGO_SERVICIO = "MASIVO_GLOSARIO_NO_CODIGO_SERVICIO";
	public final static String MASIVO_GLOSARIO_CANTIDAD_DATOS_ERROR = "MASIVO_GLOSARIO_CANTIDAD_DATOS_ERROR";
	public final static String MASIVO_AGRUPACION_NO_EXISTE = "MASIVO_AGRUPACION_NO_EXISTE";
	public final static String MASIVO_GLOSARIO_NO_EXISTE = "MASIVO_GLOSARIO_NO_EXISTE";
	public final static String MASIVO_SERVICIO_NO_EXISTE = "MASIVO_SERVICIO_NO_EXISTE";
	public final static String MASIVO_AGRUPACION_NUMBER_FORMAT_EXCEPTION = "MASIVO_AGRUPACION_NUMBER_FORMAT_EXCEPTION";
	public final static String MASIVO_GLOSARIO_NUMBER_FORMAT_EXCEPTION = "MASIVO_GLOSARIO_NUMBER_FORMAT_EXCEPTION";
	public final static String MASIVO_RANGO_INVALIDO = "MASIVO_RANGO_INVALIDO";
	public final static String MASIVO_MIN_VALUE_SERVICIO_ALEA = "MASIVO_MIN_VALUE_SERVICIO_ALEA";
	public final static String MASIVO_MAX_VALUE_SERVICIO_ALEA = "MASIVO_MAX_VALUE_SERVICIO_ALEA";
	public final static String MASIVO_ESTADO_ENTIDAD_INVALIDO = "MASIVO_ESTADO_ENTIDAD_INVALIDO";
	public final static String MASIVO_SINONIMO_OBLIGATORIO = "MASIVO_SINONIMO_OBLIGATORIO";
	public final static String MASIVO_SINONIMO_LONGITUD_MENSAJE = "MASIVO_SINONIMO_LONGITUD_MENSAJE";
	public final static String MASIVO_SINONIMO_LONGITUD = "MASIVO_SINONIMO_LONGITUD";
	public final static String MASIVO_ARCHIVO_INCORRECTO = "MASIVO_ARCHIVO_INCORRECTO";
	public final static String MASIVO_PRESTA_INSTITU_NUMBER_FORMAT_EXCEPTION = "MASIVO_PRESTA_INSTITU_NUMBER_FORMAT_EXCEPTION";
	public final static String MASIVO_COMPANIA_LONGITUD_MENSAJE = "MASIVO_COMPANIA_LONGITUD_MENSAJE";
	public final static String MASIVO_COMPANIA_LONGITUD = "MASIVO_COMPANIA_LONGITUD";
	public final static String MASIVO_CUADROMEDICO_LONGITUD_MENSAJE = "MASIVO_CUADROMEDICO_LONGITUD_MENSAJE";
	public final static String MASIVO_CUADROMEDICO_LONGITUD = "MASIVO_CUADROMEDICO_LONGITUD";
	public final static String MASIVO_CODPRESTMEDICO_LONGITUD_MENSAJE = "MASIVO_CODPRESTMEDICO_LONGITUD_MENSAJE";
	public final static String MASIVO_CODPRESTMEDICO_LONGITUD = "MASIVO_CODPRESTMEDICO_LONGITUD";
	public final static String MASIVO_CODINSTITUCION_LONGITUD_MENSAJE = "MASIVO_CODINSTITUCION_LONGITUD_MENSAJE";
	public final static String MASIVO_CODINSTITUCION_LONGITUD = "MASIVO_CODINSTITUCION_LONGITUD";
	public final static String MASIVO_CLASESERVICIO_LONGITUD_MENSAJE = "MASIVO_CLASESERVICIO_LONGITUD_MENSAJE";
	public final static String MASIVO_CLASESERVICIO_LONGITUD = "MASIVO_CLASESERVICIO_LONGITUD";
	public final static String MASIVO_CUADROSERVICIO_LONGITUD_MENSAJE = "MASIVO_CUADROSERVICIO_LONGITUD_MENSAJE";
	public final static String MASIVO_CUADROSERVICIO_LONGITUD = "MASIVO_CUADROSERVICIO_LONGITUD";
	public final static String MASIVO_ESTADO_LONGITUD_MENSAJE = "MASIVO_ESTADO_LONGITUD_MENSAJE";
	public final static String MASIVO_ESTADO_LONGITUD = "MASIVO_ESTADO_LONGITUD";
	public final static String MASIVO_PRIORIDAD_POSITIVA_MENSAJE = "MASIVO_PRIORIDAD_POSITIVA_MENSAJE";
	public final static String MASIVO_NOREQPRIO_FECHA_INICIAL_INVALIDA_MENSAJE = "MASIVO_NOREQPRIO_FECHA_INICIAL_INVALIDA_MENSAJE";
	public final static String MASIVO_NOREQPRIO_FECHA_FINAL_INVALIDA_MENSAJE = "MASIVO_NOREQPRIO_FECHA_FINAL_INVALIDA_MENSAJE";
	public final static String MASIVO_NOREQPRIO_FECHAFIN_INVALIDA_MENSAJE = "MASIVO_NOREQPRIO_FECHAFIN_FINAL_INVALIDA_MENSAJE";
	public final static String MASIVO_INSTITUCION_CANTIDAD_DATOS_ERROR = "MASIVO_INSTITUCION_CANTIDAD_DATOS_ERROR";
	public final static String MASIVO_PRIORIDAD_CANTIDAD_DATOS_ERROR = "MASIVO_PRIORIDAD_CANTIDAD_DATOS_ERROR";
	public final static String MASIVO_NOREQUIERE_CANTIDAD_DATOS_ERROR = "MASIVO_NOREQUIERE_CANTIDAD_DATOS_ERROR";
	
	
	
	//CODIGOS DE ERROR SQL PARA CARGUE MASIVO
	public final static String MASIVO_ERROR_1 = "MASIVO_ERROR_1";
	public final static String MASIVO_ERROR_2 = "MASIVO_ERROR_2";
	public final static String MASIVO_ERROR_3 = "MASIVO_ERROR_3";
	public final static String MASIVO_ERROR_4 = "MASIVO_ERROR_4";
	
	public final static String MASIVO_ERROR_1_DESCRIPCION = "MASIVO_ERROR_1_DESCRIPCION";
	public final static String MASIVO_ERROR_2_DESCRIPCION = "MASIVO_ERROR_2_DESCRIPCION";
	public final static String MASIVO_ERROR_3_DESCRIPCION = "MASIVO_ERROR_3_DESCRIPCION";
	public final static String MASIVO_ERROR_4_DESCRIPCION = "MASIVO_ERROR_4_DESCRIPCION";
	
	
	
	
	
		
	//VARIABLES UTILIZADAS COMO BOOLEANAS PERO SON DE TIPO STRING
	public final static String BOOLEAN_VERDADERO = "S";
	public final static String BOOLEAN_FALSO = "N";
	
	//PARAMETROS SERVICIO
	public final static String SERVICIO_CLASE_FARMACIA = "SERVICIO_CLASE_FARMACIA";
	public final static String SERVICIO_CON_FRECUENCIA = "SERVICIO_CON_FRECUENCIA";
	public final static String SERVICIO_CON_LATERALIDAD = "SERVICIO_CON_LATERALIDAD";
	public final static String SERVICIO_CON_SESSIONES = "SERVICIO_CON_SESSIONES";
	
	public final static String MIN_VALUE_SERVICIO_ALEA = "MIN_VALUE_SERVICIO_ALEA";
	public final static String MAX_VALUE_SERVICIO_ALEA = "MAX_VALUE_SERVICIO_ALEA";
	
	//FORMATO FECHA HORA
	public final static String FORMATO_FECHA_HORA = "FORMATO_FECHA_HORA";
	
	//MSG DE VALIDACIONES DE RADICACI�N
	public final static String RADICACION_FORM_OPCION_BUS_SERVICIO = "RADICACION_FORM_OPCION_BUS_SERVICIO";
	public final static String RADICACION_FORM_LISTA_SERVICIOS = "RADICACION_FORM_LISTA_SERVICIOS";
	public final static String RADICACION_FORM_LISTA_SERVICIOS_INGRESADOS = "RADICACION_FORM_LISTA_SERVICIOS_INGRESADOS";
	public final static String RADICACION_FORM_RAD_DOS_ORDEN_MEDICA = "RADICACION_FORM_RAD_DOS_ORDEN_MEDICA";
	public final static String RADICACION_FORM_RAD_DOS_DIAGNOSTICO = "RADICACION_FORM_RAD_DOS_DIAGNOSTICO";
	public final static String RADICACION_FORM_RAD_UNO_RADICADOR = "RADICACION_FORM_RAD_UNO_RADICADOR";
	public final static String RADICACION_FORM_EJEMPLO = "RADICACION_FORM_EJEMPLO";
	public final static String RADICACION_FORM_MODAL_DETALLE_ETIO = "RADICACION_FORM_MODAL_DETALLE_ETIO";
	public final static String EXCEPCION_VALIDACION_FORM = "EXCEPCION_VALIDACION_FORM";
	public final static String PRIORIDAD_VALIDACION_FORM = "PRIORIDAD_VALIDACION_FORM";
	public final static String CUADRO_DIRECCIONAMIENTO_FORM = "CUADRO_DIRECCIONAMIENTO_FORM";
	public final static String RADICACION_FORM_BUSQUEDA_ID = "RADICACION_FORM_BUSQUEDA_ID";
	public final static String RADICACION_FORM_BUSQUEDA_NOMBRE = "RADICACION_FORM_BUSQUEDA_NOMBRE";
	public final static String VALOR_RADICACION_ESTRUCTURADA = "VALOR_RADICACION_ESTRUCTURADA";
	public final static String RADICACION_FORM_RAD_TRES_ETIOLOGIAS_GRUPO = "RADICACION_FORM_RAD_TRES_ETIOLOGIAS_GRUPO";
	public final static String RADICACION_FORM_RAD_PRESTA_PRACTICA = "RADICACION_FORM_RAD_PRESTA_PRACTICA";
	public final static String RADICACION_FORM_RAD_PRESTA_PRACTICA_SERVICIO = "RADICACION_FORM_RAD_PRESTA_PRACTICA_SERVICIO";
	
	public final static String RADICACION_FORM_TEMP_BTN_SUP = "RADICACION_FORM_TEMP_BTN_SUP";
	public final static String RADICACION_FORM_TEMP_BTN_INF = "RADICACION_FORM_TEMP_BTN_INF";
	public final static String RADICACION_FORM_BUSQUEDA_CONTRATO = "RADICACION_FORM_BUSQUEDA_CONTRATO";
	public final static String RADICACION_FORM_BUSQUEDA_USUARIO = "RADICACION_FORM_BUSQUEDA_USUARIO";
	public final static String RADICACION_FORM_FINDER_ORDENA = "RADICACION_FORM_FINDER_ORDENA";
	public final static String RADICACION_FORM_LISTA_CONTRATO = "RADICACION_FORM_LISTA_CONTRATO";
	public final static String RADICACION_FORM_BUSQUEDA = "RADICACION_FORM_BUSQUEDA";
	public final static String RADICACION_FORM_FILE = "RADICACION_FORM_FILE";
	public final static String RADICACION_FORM_CONSULTA ="RADICACION_FORM_CONSULTA";
	public final static String RADICACION_FORM_TEMP_BTN_SUP_BASICA = "RADICACION_FORM_TEMP_BTN_SUP_BASICA";
	public final static String RADICACION_FORM_TEMP_BTN_INF_BASICA = "RADICACION_FORM_TEMP_BTN_INF_BASICA";
	
	public final static String RADICACION_NUM_ORDEN_MEDICA_VAL = "RADICACION_NUM_ORDEN_MEDICA_VAL";
	public final static String RADICACION_FORM_RAD_PRESTA_INSTITUCION = "RADICACION_FORM_RAD_PRESTA_INSTITUCION";
	public final static String CUADRO_DIRECCIONAMIENTO_MENSAJE_PREST_FORM = "CUADRO_DIRECCIONAMIENTO_MENSAJE_PREST_FORM";
	public final static String CUADRO_DIRECCIONAMIENTO_NO_REQ_FORM = "CUADRO_DIRECCIONAMIENTO_NO_REQ_FORM";
	public final static String CUADRO_DIRECCIONAMIENTO_MODAL = "CUADRO_DIRECCIONAMIENTO_MODAL";
	
	
	
	//MSG DE PARAMETRIZACION DE NEGOCIO
	public final static String FORM_AGRUPACION_SERVICIO = "FORM_AGRUPACION_SERVICIO";
	public final static String FORM_AGRUPACION_SERVICIO_DETALLE = "FORM_AGRUPACION_SERVICIO_DETALLE";
	public final static String FORM_GLOSARIO_SERVICIO = "FORM_GLOSARIO_SERVICIO";
	
	//MSG DE ESTADO Y VALIDACIONES DE AUTORIZACION AUTOMATICA
	public final static String ESTADO_MOTIVO_FORM_OPCION_GUARDAR = "ESTADO_MOTIVO_FORM_OPCION_GUARDAR";
	
	//TIPO CONSULTAS GESTION RADICACION
	
	public final static String GESTIONAR_RADICACION_POR_FILTRO_PENDIENTE = "GESTIONAR_RADICACION_POR_FILTRO_PENDIENTE";
	public final static String GESTIONAR_RADICACION_POR_NUMERO_RADICACION = "GESTIONAR_RADICACION_POR_NUMERO_RADICACION";
	
	public final static String GESTIONAR_OPCION_TIPOPRIOIRI_NORMAL = "GESTIONAR_OPCION_TIPOPRIOIRI_NORMAL";
	public final static String GESTIONAR_OPCION_TIPOPRIOIRI_PRIORI_URGENTE = "GESTIONAR_OPCION_TIPOPRIOIRI_PRIORI_URGENTE";
	
	
	//MSG DE VALIDACIONES DE GESTIONAR RADICACI�N
	
	public final static String GESTIONAR_RADICACION_FORM_CONSULTA = "GESTIONAR_RADICACION_FORM_CONSULTA";
	public final static String GESTIONAR_RADICACION_FORM = "GESTIONAR_RADICACION_FORM";
	public final static String GESTIONAR_RADICACION_MSG_NUMRADICACION = "GESTIONAR_RADICACION_MSG_NUMRADICACION";
	public final static String GESTIONAR_RADICACION_FORM_MSG = "GESTIONAR_RADICACION_FORM_MSG";
	
	
	
	//Errores en el envio de notificaciones SMS del consolidado de radicaci�n
	public final static String FLAG_ENVIO_SMS = "FLAG_ENVIO_SMS";
	public final static String FLAG_ENVIO_EMAIL = "FLAG_ENVIO_EMAIL";
	public final static String ERROR_ENVIO_SERVICIO_WEB = "ERROR_ENVIO_SERVICIO_WEB";
	public final static String CODIGO_ERROR_101 = "CODIGO_ERROR_101";
	public final static String CODIGO_ERROR_102 = "CODIGO_ERROR_102";
	public final static String CODIGO_ERROR_103 = "CODIGO_ERROR_103";
	public final static String CODIGO_ERROR_104 = "CODIGO_ERROR_104";
	public final static String CODIGO_ERROR_105 = "CODIGO_ERROR_105";
	public final static String CODIGO_ERROR_106 = "CODIGO_ERROR_106";
	public final static String CODIGO_ERROR_107 = "CODIGO_ERROR_107";
	public final static String CODIGO_ERROR_108 = "CODIGO_ERROR_108";
	public final static String CODIGO_ERROR_109 = "CODIGO_ERROR_109";
	public final static String CODIGO_ERROR_110 = "CODIGO_ERROR_110";
	
	//EMAIL
	public final static String PROP_EMAIL_MAIL_SERVER = "nma.email.mailServer";
	public final static String PROP_EMAIL_ACCOUNT_FROM = "nma.email.mailAccountFrom";
	public final static String PROP_EMAIL_NAME_FROM = "nma.email.mailNameFrom";
	public final static String PROP_EMAIL_ACCOUNT_USER = "nma.email.mailAccountUser";
	public final static String PROP_EMAIL_ACCOUNT_PASS = "nma.email.mailAccountPass";
	
	//CONFIGURACION PDF ORDENES MEDICAS BIRT
	public final static String VARIABLE_URL_REQUEST_INTERNET = "VARIABLE_URL_REQUEST_INTERNET";
	public final static String VARIABLE_PATH_INTRANET_BIRT = "VARIABLE_PATH_INTRANET_BIRT";
	public final static String VARIABLE_PATH_INTERNET_BIRT = "VARIABLE_PATH_INTERNET_BIRT";
	
	//TIPO DE MENSAJES
	public final static String TIPO_MENSAJE_INFO = "TIPO_MENSAJE_INFO";
	public final static String TIPO_MENSAJE_ERROR = "TIPO_MENSAJE_ERROR";
	public final static String TIPO_MENSAJE_WARNING = "TIPO_MENSAJE_WARNING";
		
	//MSG DE CUADRO DE DIRECCIONAMIENTO
	public final static String FORM_CUADRO_DIRECCIONAMIENTO = "FORM_CUADRO_DIRECCIONAMIENTO";
	public final static String MENS_GUARDANDO = "MENS_GUARDANDO";
	
	//MSG DE ETIOLOGIAS
	public final static String FORM_ETIOLOGIAS = "FORM_ETIOLOGIAS";
	public final static String FORM_MODAL_ETIOLOGIAS = "FORM_MODAL_ETIOLOGIAS";
	
	//MENSAJE DE INFORMACION DE USUARIO
	public final static String DIRECCION_USUARIO = "DIRECCION_USUARIO";
	public final static String CODIGO_LOCG_DANE = "CODIGO_LOCG_DANE";
	
	public final static String ERROR_GESTION_INFO_SMS = "ERROR_GESTION_INFO_SMS"; 
	
	public final static String CARACTERES_COD_PAIS_VAL = "CARACTERES_COD_PAIS_VAL"; 
	public final static String FLAG_ACTIVO_ENV_SMS = "FLAG_ACTIVO_ENV_SMS";
	public final static String FLAG_ACTIVO_ENV_MAIL = "FLAG_ACTIVO_ENV_MAIL";
	
	public final static String FORM_CONDICION_AUTORIZACION = "FORM_CONDICION_AUTORIZACION";
	public final static String FORM_CONSULTA_VOLANTES = "FORM_CONSULTA_VOLANTES";
	
	public final static String MSG_VALIDACION_EMAIL = "MSG_VALIDACION_EMAIL";
	public final static String MSG_VALIDACION_CHAR_SPECIAL = "MSG_VALIDACION_CHAR_SPECIAL";
	
	public final static String FORM_ASOCIAR_PRESTADOR = "FORM_ASOCIAR_PRESTADOR";
	
	public final static String RADICACION_ESTRUCTURADA_DIAS_ESTANCIA = "RADICACION_ESTRUCTURADA_DIAS_ESTANCIA";
	public final static String RADICACION_ESTRUCTURADA_MSG_DIAS_VALIDACION = "RADICACION_ESTRUCTURADA_MSG_DIAS_VALIDACION";
	public final static String RADICACION_ESTRUCTURADA_MSG_DIAS_VALIDACION_SESION = "RADICACION_ESTRUCTURADA_MSG_DIAS_VALIDACION_SESION";
	
	//PARAMETROS NECESARIOS PARA EL JOB DUMMY
	public final static String DUMMY_QUEUE_NAME = "DUMMY_QUEUE_NAME";
	public final static String DUMMY_QUEUE_CONNECTION_FACTORY = "DUMMY_QUEUE_CONNECTION_FACTORY";
	public final static String DUMMY_COMPANIA_ID = "DUMMY_COMPANIA_ID";
	public final static String DUMMY_PLAN_ID = "DUMMY_PLAN_ID";	
	public final static String DUMMY_CONTRATO_ID = "DUMMY_CONTRATO_ID";
	public final static String DUMMY_FAM_USR = "DUMMY_FAM_USR";
	public final static String DUMMY_NUM_USR = "DUMMY_NUM_USR";
	
	private LoginBusinessProperties(){
	}
	
	public static LoginBusinessProperties getInstance(){
		if (instance == null) {
			instance = new LoginBusinessProperties();
			loadConfig();
		}
		return instance;
	}

	/**
	 * Carga los par�metros de configuraci�n desde el archivo properties
	 * @author nagarcia@colsanitas.com
	 * @since 12/05/2008
	 */
	private static void loadConfig() {
		
		instance.config = new HashMap<String, String>();

		InputStream propsStream =  LoginBusinessProperties.class.getClassLoader().getResourceAsStream("appBusiness.properties");
		GPMProperties props = new GPMProperties();
		props.loadInputStreamProperties(propsStream);
		
		instance.config.put(SSO_SERVER_LOG_OUT, props.getProperty(SSO_SERVER_LOG_OUT));
		
		instance.config.put(PROP_NMA_APP_SERVER_TEMP_PATH, props.getProperty(PROP_NMA_APP_SERVER_TEMP_PATH));
		instance.config.put(PROP_CRON_DELETE_TMP_FILES, props.getProperty(PROP_CRON_DELETE_TMP_FILES));
		instance.config.put(PROP_CRON_DUMMY, props.getProperty(PROP_CRON_DUMMY));
		instance.config.put(PROP_CRON_TEMP_RANGO_LAST_MODIFIED, props.getProperty(PROP_CRON_TEMP_RANGO_LAST_MODIFIED));
		
		instance.config.put(FORMATO_PREFIJO_ANEXO_RADICACION_FILE_SERVER, props.getProperty(FORMATO_PREFIJO_ANEXO_RADICACION_FILE_SERVER));
		instance.config.put(FORMATO_SPLIT_RADICACION_ADJUNTO, props.getProperty(FORMATO_SPLIT_RADICACION_ADJUNTO));
		
		instance.config.put(ID_DOMAIN, props.getProperty(ID_DOMAIN));
		
		instance.config.put(MIN_SIZE_FILE, props.getProperty(MIN_SIZE_FILE));
		instance.config.put(MAX_SIZE_FILE_ADJUNTO_OM, props.getProperty(MAX_SIZE_FILE_ADJUNTO_OM));
		instance.config.put(MAX_SIZE_FILE_CARGUE_MASIVO, props.getProperty(MAX_SIZE_FILE_CARGUE_MASIVO));
		
		instance.config.put(FORMATO_DATE_APLICACION_HORA, props.getProperty(FORMATO_DATE_APLICACION_HORA));
		
		instance.config.put(FORMATO_PREFIJO_RESPUESTA_CARGUE_MASIVO, props.getProperty(FORMATO_PREFIJO_RESPUESTA_CARGUE_MASIVO));
		instance.config.put(NOMBRE_ARCHIVO_RES_MASIVO_AGRUPACION_SERVICIO, props.getProperty(NOMBRE_ARCHIVO_RES_MASIVO_AGRUPACION_SERVICIO));
		instance.config.put(NOMBRE_ARCHIVO_RES_MASIVO_GLOSARIO_SERVICIO, props.getProperty(NOMBRE_ARCHIVO_RES_MASIVO_GLOSARIO_SERVICIO));
		instance.config.put(NOMBRE_ARCHIVO_RES_MASIVO_PRESTADOR_INSTITUCION, props.getProperty(NOMBRE_ARCHIVO_RES_MASIVO_PRESTADOR_INSTITUCION));
		instance.config.put(NOMBRE_ARCHIVO_RES_MASIVO_PRESTADOR_PRIORIDAD, props.getProperty(NOMBRE_ARCHIVO_RES_MASIVO_PRESTADOR_PRIORIDAD));
		instance.config.put(NOMBRE_ARCHIVO_RES_MASIVO_PRESTADOR_NO_REQ_AUT, props.getProperty(NOMBRE_ARCHIVO_RES_MASIVO_PRESTADOR_NO_REQ_AUT));
		

		instance.config.put(RADICACION_IDENTIFICACION, props.getProperty(RADICACION_IDENTIFICACION));
		instance.config.put(RADICACION_CONTRATO, props.getProperty(RADICACION_CONTRATO));
		instance.config.put(RADICACION_NOMBRE, props.getProperty(RADICACION_NOMBRE));
		
		instance.config.put(RADICACION_SERVICIOS_DESCRIPCION, props.getProperty(RADICACION_SERVICIOS_DESCRIPCION));
		instance.config.put(RADICACION_SERVICIOS_CODIGO, props.getProperty(RADICACION_SERVICIOS_CODIGO));
		instance.config.put(TIPO_OBSERVACION_GESTION, props.getProperty(TIPO_OBSERVACION_GESTION));
		instance.config.put(TIPO_OBSERVACION_PRESTADOR, props.getProperty(TIPO_OBSERVACION_PRESTADOR));
		
		instance.config.put(ESTADO_ACTIVO_ENTIDAD, props.getProperty(ESTADO_ACTIVO_ENTIDAD));
		instance.config.put(ESTADO_INACTIVO_ENTIDAD, props.getProperty(ESTADO_INACTIVO_ENTIDAD));
		
		instance.config.put(ESTADO_SERVICIO_RA, props.getProperty(ESTADO_SERVICIO_RA));
		instance.config.put(VALOR_ESTADO_INICIAL_RA, props.getProperty(VALOR_ESTADO_INICIAL_RA));
		instance.config.put(MOTIVO_SERVICIO_RA, props.getProperty(MOTIVO_SERVICIO_RA));
		instance.config.put(VALOR_MOTIVO_INICIAL_RA, props.getProperty(VALOR_MOTIVO_INICIAL_RA));
		
		instance.config.put(CANTIDAD_MAX_ARCHIVOS_UPLOAD_MASIVO, props.getProperty(CANTIDAD_MAX_ARCHIVOS_UPLOAD_MASIVO));
		instance.config.put(CANTIDAD_MAX_ARCHIVOS_UPLOAD_ANEXOS, props.getProperty(CANTIDAD_MAX_ARCHIVOS_UPLOAD_ANEXOS));
		instance.config.put(CONDICION_ROL_VISIBLE_SI, props.getProperty(CONDICION_ROL_VISIBLE_SI));
		instance.config.put(CONCATENA_RADICADOR, props.getProperty(CONCATENA_RADICADOR));
		instance.config.put(TIPO_RADICACION, props.getProperty(TIPO_RADICACION));
		instance.config.put(ESTADO_RADICACION, props.getProperty(ESTADO_RADICACION));
		instance.config.put(MOTIVO_RADICACION, props.getProperty(MOTIVO_RADICACION));
		instance.config.put(CONSULTA_RADICACION_POR_IDENTIFICACION, props.getProperty(CONSULTA_RADICACION_POR_IDENTIFICACION));
		instance.config.put(CONSULTA_RADICACION_POR_COMPANIA, props.getProperty(CONSULTA_RADICACION_POR_COMPANIA));
		instance.config.put(CONSULTA_RADICACION_POR_CONTRATO, props.getProperty(CONSULTA_RADICACION_POR_CONTRATO));
		instance.config.put(CONSULTA_RADICACION_POR_RADICACION, props.getProperty(CONSULTA_RADICACION_POR_RADICACION));
		
		instance.config.put(ROL_USUARIO, props.getProperty(ROL_USUARIO));
		instance.config.put(ROL_PRESTADOR_RADICADOR, props.getProperty(ROL_PRESTADOR_RADICADOR));
		instance.config.put(ROL_FUNCIONARIO, props.getProperty(ROL_FUNCIONARIO));
		instance.config.put(LOGIN_USER_SIN_PERMISOS, props.getProperty(LOGIN_USER_SIN_PERMISOS));
		instance.config.put(ROL_ITERADOR_SIMULADOR, props.getProperty(ROL_ITERADOR_SIMULADOR));
		
		instance.config.put(ROL_USUARIO_GAUDI, props.getProperty(ROL_USUARIO_GAUDI));
		instance.config.put(ROL_PRESTADOR_RADICADOR_GAUDI, props.getProperty(ROL_PRESTADOR_RADICADOR_GAUDI));
		instance.config.put(ROL_FUNCIONARIO_GAUDI, props.getProperty(ROL_FUNCIONARIO_GAUDI));
		
		instance.config.put(CARGA_PRESTADORES,props.getProperty(CARGA_PRESTADORES));
		instance.config.put(INFORMACION_CONTACTO_PRESTADOR,props.getProperty(INFORMACION_CONTACTO_PRESTADOR));
		instance.config.put(INFRAESTRUCTURA_OSI,props.getProperty(INFRAESTRUCTURA_OSI));
		instance.config.put(INSTITUCIONES_PRESTADORES_NATURALES,props.getProperty(INSTITUCIONES_PRESTADORES_NATURALES));
		instance.config.put(MENSAJES_PRESTADOR,props.getProperty(MENSAJES_PRESTADOR));
		instance.config.put(PRESTADORES_NO_ORDENANTES,props.getProperty(PRESTADORES_NO_ORDENANTES));
		instance.config.put(PRESTADORES_NO_VISIBLES,props.getProperty(PRESTADORES_NO_VISIBLES));
		instance.config.put(PRIORIDAD_PRESTADORES,props.getProperty(PRIORIDAD_PRESTADORES));
		instance.config.put(SERVICIOS_NO_REQUIEREN_AUTORIZACION_PRESTADOR,props.getProperty(SERVICIOS_NO_REQUIEREN_AUTORIZACION_PRESTADOR));
		
		instance.config.put(CHARSET_CARGUE_MASIVO,props.getProperty(CHARSET_CARGUE_MASIVO));
		instance.config.put(TOTAL_LINEAS_ARCHIVO,props.getProperty(TOTAL_LINEAS_ARCHIVO));
		instance.config.put(TOTAL_LINEAS_ARCHIVO_ERROR,props.getProperty(TOTAL_LINEAS_ARCHIVO_ERROR));
		instance.config.put(TOTAL_LINEAS_ARCHIVO_EXITO,props.getProperty(TOTAL_LINEAS_ARCHIVO_EXITO));
		instance.config.put(ERROR_LINEA_ARCHIVO_MASIVO,props.getProperty(ERROR_LINEA_ARCHIVO_MASIVO));
		
		instance.config.put(MASIVO_AGRUPACION_NO_RANGO_COD_SERV,props.getProperty(MASIVO_AGRUPACION_NO_RANGO_COD_SERV));
		instance.config.put(MASIVO_AGRUPACION_RANGO_COD_SERV,props.getProperty(MASIVO_AGRUPACION_RANGO_COD_SERV));
		instance.config.put(MASIVO_AGRUPACION_RANGO_INCOMPLETO,props.getProperty(MASIVO_AGRUPACION_RANGO_INCOMPLETO));
		instance.config.put(MASIVO_AGRUPACION_CANTIDAD_DATOS_ERROR,props.getProperty(MASIVO_AGRUPACION_CANTIDAD_DATOS_ERROR));
		instance.config.put(MASIVO_AGRUPACION_NO_CODIGO_ESTADO,props.getProperty(MASIVO_AGRUPACION_NO_CODIGO_ESTADO));
		instance.config.put(MASIVO_AGRUPACION_NO_EXISTE,props.getProperty(MASIVO_AGRUPACION_NO_EXISTE));
		instance.config.put(MASIVO_GLOSARIO_NO_EXISTE,props.getProperty(MASIVO_GLOSARIO_NO_EXISTE));
		instance.config.put(MASIVO_GLOSARIO_CANTIDAD_DATOS_ERROR,props.getProperty(MASIVO_GLOSARIO_CANTIDAD_DATOS_ERROR));
		instance.config.put(MASIVO_SERVICIO_NO_EXISTE,props.getProperty(MASIVO_SERVICIO_NO_EXISTE));
		instance.config.put(MASIVO_AGRUPACION_NUMBER_FORMAT_EXCEPTION,props.getProperty(MASIVO_AGRUPACION_NUMBER_FORMAT_EXCEPTION));
		instance.config.put(MASIVO_GLOSARIO_NUMBER_FORMAT_EXCEPTION,props.getProperty(MASIVO_GLOSARIO_NUMBER_FORMAT_EXCEPTION));
		instance.config.put(MASIVO_GLOSARIO_NO_CODIGO_SERVICIO,props.getProperty(MASIVO_GLOSARIO_NO_CODIGO_SERVICIO));
		instance.config.put(MASIVO_SINONIMO_OBLIGATORIO,props.getProperty(MASIVO_SINONIMO_OBLIGATORIO));
		instance.config.put(MASIVO_SINONIMO_LONGITUD_MENSAJE,props.getProperty(MASIVO_SINONIMO_LONGITUD_MENSAJE));
		instance.config.put(MASIVO_SINONIMO_LONGITUD,props.getProperty(MASIVO_SINONIMO_LONGITUD));
		instance.config.put(MASIVO_COMPANIA_LONGITUD_MENSAJE,props.getProperty(MASIVO_COMPANIA_LONGITUD_MENSAJE));
		instance.config.put(MASIVO_COMPANIA_LONGITUD,props.getProperty(MASIVO_COMPANIA_LONGITUD));
		instance.config.put(MASIVO_CODPRESTMEDICO_LONGITUD_MENSAJE,props.getProperty(MASIVO_CODPRESTMEDICO_LONGITUD_MENSAJE));
		instance.config.put(MASIVO_CODPRESTMEDICO_LONGITUD,props.getProperty(MASIVO_CODPRESTMEDICO_LONGITUD));
		instance.config.put(MASIVO_CODINSTITUCION_LONGITUD_MENSAJE,props.getProperty(MASIVO_CODINSTITUCION_LONGITUD_MENSAJE));
		instance.config.put(MASIVO_CODINSTITUCION_LONGITUD,props.getProperty(MASIVO_CODINSTITUCION_LONGITUD));
		instance.config.put(MASIVO_CLASESERVICIO_LONGITUD_MENSAJE,props.getProperty(MASIVO_CLASESERVICIO_LONGITUD_MENSAJE));
		instance.config.put(MASIVO_CLASESERVICIO_LONGITUD,props.getProperty(MASIVO_CLASESERVICIO_LONGITUD));
		instance.config.put(MASIVO_CUADROSERVICIO_LONGITUD_MENSAJE,props.getProperty(MASIVO_CUADROSERVICIO_LONGITUD_MENSAJE));
		instance.config.put(MASIVO_CUADROSERVICIO_LONGITUD,props.getProperty(MASIVO_CUADROSERVICIO_LONGITUD));
		instance.config.put(MASIVO_ESTADO_LONGITUD_MENSAJE,props.getProperty(MASIVO_ESTADO_LONGITUD_MENSAJE));
		instance.config.put(MASIVO_ESTADO_LONGITUD,props.getProperty(MASIVO_ESTADO_LONGITUD));
		instance.config.put(MASIVO_PRIORIDAD_POSITIVA_MENSAJE,props.getProperty(MASIVO_PRIORIDAD_POSITIVA_MENSAJE));
		instance.config.put(MASIVO_NOREQPRIO_FECHA_INICIAL_INVALIDA_MENSAJE,props.getProperty(MASIVO_NOREQPRIO_FECHA_INICIAL_INVALIDA_MENSAJE));
		instance.config.put(MASIVO_NOREQPRIO_FECHA_FINAL_INVALIDA_MENSAJE,props.getProperty(MASIVO_NOREQPRIO_FECHA_FINAL_INVALIDA_MENSAJE));
		instance.config.put(MASIVO_NOREQPRIO_FECHAFIN_INVALIDA_MENSAJE,props.getProperty(MASIVO_NOREQPRIO_FECHAFIN_INVALIDA_MENSAJE));
		instance.config.put(MASIVO_INSTITUCION_CANTIDAD_DATOS_ERROR,props.getProperty(MASIVO_INSTITUCION_CANTIDAD_DATOS_ERROR));
		instance.config.put(MASIVO_PRIORIDAD_CANTIDAD_DATOS_ERROR,props.getProperty(MASIVO_PRIORIDAD_CANTIDAD_DATOS_ERROR));
		instance.config.put(MASIVO_NOREQUIERE_CANTIDAD_DATOS_ERROR,props.getProperty(MASIVO_NOREQUIERE_CANTIDAD_DATOS_ERROR));
		
		
		
		
		
				
		instance.config.put(MASIVO_ERROR_1,props.getProperty(MASIVO_ERROR_1));
		instance.config.put(MASIVO_ERROR_2,props.getProperty(MASIVO_ERROR_2));
		instance.config.put(MASIVO_ERROR_3,props.getProperty(MASIVO_ERROR_3));
		instance.config.put(MASIVO_ERROR_4,props.getProperty(MASIVO_ERROR_4));
		
		instance.config.put(MASIVO_ERROR_1_DESCRIPCION,props.getProperty(MASIVO_ERROR_1_DESCRIPCION));
		instance.config.put(MASIVO_ERROR_2_DESCRIPCION,props.getProperty(MASIVO_ERROR_2_DESCRIPCION));
		instance.config.put(MASIVO_ERROR_3_DESCRIPCION,props.getProperty(MASIVO_ERROR_3_DESCRIPCION));
		instance.config.put(MASIVO_ERROR_4_DESCRIPCION,props.getProperty(MASIVO_ERROR_4_DESCRIPCION));
		
		
				
		instance.config.put(MASIVO_CUADROMEDICO_LONGITUD_MENSAJE,props.getProperty(MASIVO_CUADROMEDICO_LONGITUD_MENSAJE));
		instance.config.put(MASIVO_CUADROMEDICO_LONGITUD,props.getProperty(MASIVO_CUADROMEDICO_LONGITUD));
		
		instance.config.put(MASIVO_RANGO_INVALIDO,props.getProperty(MASIVO_RANGO_INVALIDO));
		instance.config.put(MASIVO_MIN_VALUE_SERVICIO_ALEA,props.getProperty(MASIVO_MIN_VALUE_SERVICIO_ALEA));
		instance.config.put(MASIVO_MAX_VALUE_SERVICIO_ALEA,props.getProperty(MASIVO_MAX_VALUE_SERVICIO_ALEA));
		instance.config.put(MASIVO_ESTADO_ENTIDAD_INVALIDO,props.getProperty(MASIVO_ESTADO_ENTIDAD_INVALIDO));
		instance.config.put(MASIVO_ARCHIVO_INCORRECTO,props.getProperty(MASIVO_ARCHIVO_INCORRECTO));
		
		instance.config.put(SERVICIO_CLASE_FARMACIA,props.getProperty(SERVICIO_CLASE_FARMACIA));
		instance.config.put(SERVICIO_CON_FRECUENCIA,props.getProperty(SERVICIO_CON_FRECUENCIA));
		instance.config.put(SERVICIO_CON_LATERALIDAD,props.getProperty(SERVICIO_CON_LATERALIDAD));
		instance.config.put(SERVICIO_CON_SESSIONES,props.getProperty(SERVICIO_CON_SESSIONES));
		
		instance.config.put(MIN_VALUE_SERVICIO_ALEA,props.getProperty(MIN_VALUE_SERVICIO_ALEA));
		instance.config.put(MAX_VALUE_SERVICIO_ALEA,props.getProperty(MAX_VALUE_SERVICIO_ALEA));
		
		instance.config.put(FORMATO_FECHA_HORA,props.getProperty(FORMATO_FECHA_HORA));
		
		//msg Validaciones de radicacion
		instance.config.put(RADICACION_FORM_OPCION_BUS_SERVICIO, props.getProperty(RADICACION_FORM_OPCION_BUS_SERVICIO));
		instance.config.put(RADICACION_FORM_LISTA_SERVICIOS, props.getProperty(RADICACION_FORM_LISTA_SERVICIOS));
		instance.config.put(RADICACION_FORM_LISTA_SERVICIOS_INGRESADOS, props.getProperty(RADICACION_FORM_LISTA_SERVICIOS_INGRESADOS));
		instance.config.put(RADICACION_FORM_RAD_DOS_ORDEN_MEDICA, props.getProperty(RADICACION_FORM_RAD_DOS_ORDEN_MEDICA));
		instance.config.put(RADICACION_FORM_RAD_DOS_DIAGNOSTICO, props.getProperty(RADICACION_FORM_RAD_DOS_DIAGNOSTICO));
		instance.config.put(RADICACION_FORM_RAD_UNO_RADICADOR, props.getProperty(RADICACION_FORM_RAD_UNO_RADICADOR));
		instance.config.put(RADICACION_FORM_EJEMPLO, props.getProperty(RADICACION_FORM_EJEMPLO));
		instance.config.put(RADICACION_FORM_MODAL_DETALLE_ETIO, props.getProperty(RADICACION_FORM_MODAL_DETALLE_ETIO));
		instance.config.put(EXCEPCION_VALIDACION_FORM, props.getProperty(EXCEPCION_VALIDACION_FORM));
		instance.config.put(PRIORIDAD_VALIDACION_FORM, props.getProperty(PRIORIDAD_VALIDACION_FORM));
		instance.config.put(CUADRO_DIRECCIONAMIENTO_FORM, props.getProperty(CUADRO_DIRECCIONAMIENTO_FORM));
		instance.config.put(RADICACION_FORM_BUSQUEDA_ID, props.getProperty(RADICACION_FORM_BUSQUEDA_ID));
		instance.config.put(RADICACION_FORM_FILE, props.getProperty(RADICACION_FORM_FILE));
		instance.config.put(RADICACION_FORM_BUSQUEDA_NOMBRE, props.getProperty(RADICACION_FORM_BUSQUEDA_NOMBRE));
		instance.config.put(VALOR_RADICACION_ESTRUCTURADA, props.getProperty(VALOR_RADICACION_ESTRUCTURADA));
		instance.config.put(RADICACION_FORM_RAD_TRES_ETIOLOGIAS_GRUPO, props.getProperty(RADICACION_FORM_RAD_TRES_ETIOLOGIAS_GRUPO));
		instance.config.put(RADICACION_FORM_RAD_PRESTA_PRACTICA, props.getProperty(RADICACION_FORM_RAD_PRESTA_PRACTICA));
		instance.config.put(RADICACION_FORM_RAD_PRESTA_PRACTICA_SERVICIO, props.getProperty(RADICACION_FORM_RAD_PRESTA_PRACTICA_SERVICIO));
		instance.config.put(RADICACION_FORM_TEMP_BTN_SUP, props.getProperty(RADICACION_FORM_TEMP_BTN_SUP));
		instance.config.put(RADICACION_FORM_TEMP_BTN_INF, props.getProperty(RADICACION_FORM_TEMP_BTN_INF));
		instance.config.put(RADICACION_FORM_BUSQUEDA_CONTRATO, props.getProperty(RADICACION_FORM_BUSQUEDA_CONTRATO));
		instance.config.put(RADICACION_FORM_BUSQUEDA_USUARIO, props.getProperty(RADICACION_FORM_BUSQUEDA_USUARIO));
		instance.config.put(RADICACION_FORM_FINDER_ORDENA, props.getProperty(RADICACION_FORM_FINDER_ORDENA));
		instance.config.put(RADICACION_FORM_LISTA_CONTRATO, props.getProperty(RADICACION_FORM_LISTA_CONTRATO));
		instance.config.put(RADICACION_TIPO, props.getProperty(RADICACION_TIPO));
		instance.config.put(RADICACION_FORM_RAD_PRESTA_INSTITUCION, props.getProperty(RADICACION_FORM_RAD_PRESTA_INSTITUCION));
		instance.config.put(CUADRO_DIRECCIONAMIENTO_MENSAJE_PREST_FORM, props.getProperty(CUADRO_DIRECCIONAMIENTO_MENSAJE_PREST_FORM));
		instance.config.put(CUADRO_DIRECCIONAMIENTO_NO_REQ_FORM, props.getProperty(CUADRO_DIRECCIONAMIENTO_NO_REQ_FORM));
		instance.config.put(CUADRO_DIRECCIONAMIENTO_MODAL, props.getProperty(CUADRO_DIRECCIONAMIENTO_MODAL));
		instance.config.put(RADICACION_FORM_CONSULTA, props.getProperty(RADICACION_FORM_CONSULTA));
		instance.config.put(RADICACION_FORM_TEMP_BTN_SUP_BASICA, props.getProperty(RADICACION_FORM_TEMP_BTN_SUP_BASICA));
		instance.config.put(RADICACION_FORM_TEMP_BTN_INF_BASICA, props.getProperty(RADICACION_FORM_TEMP_BTN_INF_BASICA));
		
		
		
		instance.config.put(FORM_AGRUPACION_SERVICIO, props.getProperty(FORM_AGRUPACION_SERVICIO));
		instance.config.put(FORM_AGRUPACION_SERVICIO_DETALLE, props.getProperty(FORM_AGRUPACION_SERVICIO_DETALLE));
		instance.config.put(FORM_GLOSARIO_SERVICIO, props.getProperty(FORM_GLOSARIO_SERVICIO));
		
		//msg estado validaciones autorizacion automatica
		instance.config.put(ESTADO_MOTIVO_FORM_OPCION_GUARDAR, props.getProperty(ESTADO_MOTIVO_FORM_OPCION_GUARDAR));
		
		//msg cuadro de direccionamiento
		instance.config.put(FORM_CUADRO_DIRECCIONAMIENTO, props.getProperty(FORM_CUADRO_DIRECCIONAMIENTO));
		
		//msg etiologias
		instance.config.put(FORM_ETIOLOGIAS, props.getProperty(FORM_ETIOLOGIAS));
		instance.config.put(FORM_MODAL_ETIOLOGIAS, props.getProperty(FORM_MODAL_ETIOLOGIAS));
		
		//Gestionar Radicacion
		instance.config.put(GESTIONAR_RADICACION_POR_FILTRO_PENDIENTE,props.getProperty(GESTIONAR_RADICACION_POR_FILTRO_PENDIENTE));
		instance.config.put(GESTIONAR_RADICACION_POR_NUMERO_RADICACION,props.getProperty(GESTIONAR_RADICACION_POR_NUMERO_RADICACION));
		instance.config.put(GESTIONAR_OPCION_TIPOPRIOIRI_NORMAL,props.getProperty(GESTIONAR_OPCION_TIPOPRIOIRI_NORMAL));
		instance.config.put(GESTIONAR_OPCION_TIPOPRIOIRI_PRIORI_URGENTE,props.getProperty(GESTIONAR_OPCION_TIPOPRIOIRI_PRIORI_URGENTE));
		
		//msg Validaciones de radicacion
		instance.config.put(GESTIONAR_RADICACION_FORM_CONSULTA,props.getProperty(GESTIONAR_RADICACION_FORM_CONSULTA));
		instance.config.put(GESTIONAR_RADICACION_FORM,props.getProperty(GESTIONAR_RADICACION_FORM));
		instance.config.put(GESTIONAR_RADICACION_MSG_NUMRADICACION,props.getProperty(GESTIONAR_RADICACION_MSG_NUMRADICACION));
		instance.config.put(GESTIONAR_RADICACION_FORM_MSG,props.getProperty(GESTIONAR_RADICACION_FORM_MSG));
		
		
		//Errores en el envio de notificaciones SMS del consolidado de radicaci�n
		instance.config.put(FLAG_ENVIO_SMS, props.getProperty(FLAG_ENVIO_SMS));
		instance.config.put(FLAG_ENVIO_EMAIL, props.getProperty(FLAG_ENVIO_EMAIL));
		instance.config.put(ERROR_ENVIO_SERVICIO_WEB, props.getProperty(ERROR_ENVIO_SERVICIO_WEB));
		instance.config.put(CODIGO_ERROR_101, props.getProperty(CODIGO_ERROR_101));
		instance.config.put(CODIGO_ERROR_102, props.getProperty(CODIGO_ERROR_102));
		instance.config.put(CODIGO_ERROR_103, props.getProperty(CODIGO_ERROR_103));
		instance.config.put(CODIGO_ERROR_104, props.getProperty(CODIGO_ERROR_104));
		instance.config.put(CODIGO_ERROR_105, props.getProperty(CODIGO_ERROR_105));
		instance.config.put(CODIGO_ERROR_106, props.getProperty(CODIGO_ERROR_106));
		instance.config.put(CODIGO_ERROR_107, props.getProperty(CODIGO_ERROR_107));
		instance.config.put(CODIGO_ERROR_108, props.getProperty(CODIGO_ERROR_108));
		instance.config.put(CODIGO_ERROR_109, props.getProperty(CODIGO_ERROR_109));
		instance.config.put(CODIGO_ERROR_110, props.getProperty(CODIGO_ERROR_110));
		
		instance.config.put(PROP_EMAIL_MAIL_SERVER, props.getProperty(PROP_EMAIL_MAIL_SERVER));
		instance.config.put(PROP_EMAIL_ACCOUNT_FROM, props.getProperty(PROP_EMAIL_ACCOUNT_FROM));
		instance.config.put(PROP_EMAIL_NAME_FROM, props.getProperty(PROP_EMAIL_NAME_FROM));
		instance.config.put(PROP_EMAIL_ACCOUNT_USER, props.getProperty(PROP_EMAIL_ACCOUNT_USER));
		instance.config.put(PROP_EMAIL_ACCOUNT_PASS, props.getProperty(PROP_EMAIL_ACCOUNT_PASS));
		
		instance.config.put(VARIABLE_URL_REQUEST_INTERNET, props.getProperty(VARIABLE_URL_REQUEST_INTERNET));
		instance.config.put(VARIABLE_PATH_INTRANET_BIRT, props.getProperty(VARIABLE_PATH_INTRANET_BIRT));
		instance.config.put(VARIABLE_PATH_INTERNET_BIRT, props.getProperty(VARIABLE_PATH_INTERNET_BIRT));
		
		instance.config.put(TIPO_MENSAJE_INFO, props.getProperty(TIPO_MENSAJE_INFO));
		instance.config.put(TIPO_MENSAJE_ERROR, props.getProperty(TIPO_MENSAJE_ERROR));
		instance.config.put(TIPO_MENSAJE_WARNING, props.getProperty(TIPO_MENSAJE_WARNING));
		instance.config.put(DIRECCION_USUARIO, props.getProperty(DIRECCION_USUARIO));
		instance.config.put(CODIGO_LOCG_DANE, props.getProperty(CODIGO_LOCG_DANE));
		
		instance.config.put(ERROR_GESTION_INFO_SMS, props.getProperty(ERROR_GESTION_INFO_SMS));
		
		instance.config.put(CARACTERES_COD_PAIS_VAL, props.getProperty(CARACTERES_COD_PAIS_VAL));
		instance.config.put(FLAG_ACTIVO_ENV_SMS, props.getProperty(FLAG_ACTIVO_ENV_SMS));
		instance.config.put(FLAG_ACTIVO_ENV_MAIL, props.getProperty(FLAG_ACTIVO_ENV_MAIL));
		
		instance.config.put(RADICACION_FORM_BUSQUEDA, props.getProperty(RADICACION_FORM_BUSQUEDA));
		instance.config.put(RADICACION_NUM_ORDEN_MEDICA_VAL, props.getProperty(RADICACION_NUM_ORDEN_MEDICA_VAL));
		
		instance.config.put(FORM_CONDICION_AUTORIZACION, props.getProperty(FORM_CONDICION_AUTORIZACION));
		instance.config.put(FORM_CONSULTA_VOLANTES, props.getProperty(FORM_CONSULTA_VOLANTES));
		
		instance.config.put(MSG_VALIDACION_EMAIL, props.getProperty(MSG_VALIDACION_EMAIL));
		instance.config.put(MSG_VALIDACION_CHAR_SPECIAL, props.getProperty(MSG_VALIDACION_CHAR_SPECIAL));
		
		instance.config.put(FORM_ASOCIAR_PRESTADOR, props.getProperty(FORM_ASOCIAR_PRESTADOR));
		
		instance.config.put(RADICACION_ESTRUCTURADA_DIAS_ESTANCIA, props.getProperty(RADICACION_ESTRUCTURADA_DIAS_ESTANCIA));
		instance.config.put(RADICACION_ESTRUCTURADA_MSG_DIAS_VALIDACION, props.getProperty(RADICACION_ESTRUCTURADA_MSG_DIAS_VALIDACION));
		instance.config.put(RADICACION_ESTRUCTURADA_MSG_DIAS_VALIDACION_SESION, props.getProperty(RADICACION_ESTRUCTURADA_MSG_DIAS_VALIDACION_SESION));
		
		//PARAMETROS NECESARIOS PARA EL JOB DUMMY		
		instance.config.put(DUMMY_QUEUE_NAME, props.getProperty(DUMMY_QUEUE_NAME));
		instance.config.put(DUMMY_QUEUE_CONNECTION_FACTORY, props.getProperty(DUMMY_QUEUE_CONNECTION_FACTORY));
		instance.config.put(DUMMY_COMPANIA_ID, props.getProperty(DUMMY_COMPANIA_ID));
		instance.config.put(DUMMY_PLAN_ID, props.getProperty(DUMMY_PLAN_ID));
		instance.config.put(DUMMY_CONTRATO_ID, props.getProperty(DUMMY_CONTRATO_ID));
		instance.config.put(DUMMY_FAM_USR, props.getProperty(DUMMY_FAM_USR));
		instance.config.put(DUMMY_NUM_USR, props.getProperty(DUMMY_NUM_USR));
		
	}
	
	/**
	 * Obtiene el valor del parametro de entrada
	 * @author gstovar@colsanitas.com
	 * @since 24/03/2011
	 */
	public String getParameter(String parameterKey) {
		return config.get(parameterKey);
	}
}